apiVersion: v1
kind: Service
metadata:
  name: mycv-service
  namespace: mfeher2
spec:
  type: NodePort
  selector:
    app: mycv
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007   # Must be between 30000-32767

